#!/bin/bash

commands=("Compare Documents" "Duplicate Line Remover" "Find Word" "Find Word Archive" "Keyword Line Extractor" "Keyword Line Extractor Recursive" "Replace Keyword" "Replace Keyword Recursive" "Quit")

selected=0

# Function to display the list and highlight the selected item
display_list() {
    clear
    echo -e "\033[1m  Document Tools\033[0m\n  --------------"
    for i in "${!commands[@]}"; do
        if [ $i -eq $selected ]; then
            if [ "${commands[$i]}" == "Quit" ]; then
                echo -e "\033[1m➤ ${commands[$i]}\033[0m\n"
            else
                echo -e "\033[1m➤ ${commands[$i]}\033[0m\n"
            fi
        else
            echo -e "  ${commands[$i]}\n"
        fi
    done
}

# Function to execute the selected command
execute_command() {
    case ${commands[$selected]} in
        "Compare Documents") 
            # Add your command logic here
            python3 Document-Tools/tools/compare-documents.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Duplicate Line Remover") 
            # Add your command logic here
            python3 Document-Tools/tools/duplicate-line-remover.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Find Word") 
            # Add your command logic here
            python3 Document-Tools/find-word.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Find Word Archive") 
            # Add your command logic here
            python3 Document-Tools/find-word-archive.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Keyword Line Extractor") 
            # Add your command logic here
            python3 Document-Tools/keyword-line-extractor.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Keyword Line Extractor Recursive") 
            # Add your command logic here
            python3 Document-Tools/keyword-line-extractor-r.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Replace Keyword") 
            # Add your command logic here
            python3 Document-Tools/replace-keyword.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Replace Keyword Recursive") 
            # Add your command logic here
            python3 Document-Tools/replace-keyword-r.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Quit") 
            echo -e "\n\033[1mExiting script\033[0m"
            exit 0
            ;;
        *) 
            echo -e "\nInvalid selection"
            ;;
    esac
}

# Main loop
while true; do
    display_list

    read -sn 1 key

    case $key in
        "A") ((selected--)); [ $selected -lt 0 ] && selected=$(( ${#commands[@]} - 1 ));;
        "B") ((selected++)); [ $selected -ge ${#commands[@]} ] && selected=0 ;;
        "") execute_command ;;
        *) ;;
    esac
done
